apply from: "../gradle/loader.gradle"

architectury.fabric()

configurations {
    developmentFabric.extendsFrom common
}

repositories {
    maven {
        url = 'https://maven.terraformersmc.com/releases/'
        content { includeGroup "com.terraformersmc"}
    }

    maven {
        url = 'https://maven.gegy.dev'
    }
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:$project.fabric_loader_version"

    // Fabric API. This is technically optional, but you probably want it anyway.
    modImplementation "net.fabricmc.fabric-api:fabric-api:$project.fabric_version"

    modImplementation "dev.architectury:architectury-fabric:$project.architectury_version"

    modImplementation "com.terraformersmc:modmenu:$project.modmenu_version"

    shadowBundle project(path: ':common', configuration: 'transformProductionFabric')
}

processResources {
    inputs.property 'version', project.version

    filesMatching('fabric.mod.json') {
        expand version: project.version
    }
}