plugins {
	id "architectury-plugin" version "3.4-SNAPSHOT"
	id "dev.architectury.loom" version "1.7-SNAPSHOT" apply false
	id "io.github.juuxel.loom-vineflower" version "1.+" apply false
	id "com.github.johnrengelman.shadow" version "8.1.1" apply false
	id "maven-publish"
}

def targetJavaVersion = 21

architectury {
	minecraft = project.minecraft_version
}

allprojects {
	group = rootProject.maven_group
	version = "${rootProject.mod_version}+${project.minecraft_version}"
}

subprojects {
	apply plugin: 'dev.architectury.loom'
	apply plugin: 'architectury-plugin'
	apply plugin: 'maven-publish'

//	base {
//		// Set up a suffixed format for the mod jar names, e.g. `example-fabric`.
//		archivesName = "$rootProject.archives_name-$project.name"
//	}

	repositories {
		// Add repositories to retrieve artifacts from in here.
		// You should only use this when depending on other mods because
		// Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
		// See https://docs.gradle.org/current/userguide/declaring_repositories.html
		// for more information about repositories.
	}

	dependencies {
		minecraft "net.minecraft:minecraft:$rootProject.minecraft_version"
		mappings loom.layered {
			it.mappings("net.fabricmc:yarn:${minecraft_version}+build.$rootProject.mappings:v2")
			it.mappings("dev.architectury:yarn-mappings-patch-neoforge:$rootProject.mappings_patch")
		}
	}

	java {
		// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
		// if it is present.
		// If you remove this line, sources will not be generated.
		withSourcesJar()

		sourceCompatibility = JavaVersion.toVersion(targetJavaVersion)
		targetCompatibility = JavaVersion.toVersion(targetJavaVersion)
	}

	tasks.withType(JavaCompile).configureEach {
		it.options.encoding('UTF-8')
		it.options.deprecation(true)
		it.options.incremental(true)

		it.options.release = targetJavaVersion
	}
}
