# file suppress inspection "UnusedProperty"

# Versioning
minecraft_version = 1.21.4
mappings = 1
mappings_patch = 1.21+build.4
fabric_loader_version = 0.16.10

neoforge_version = 21.4.9-beta
fabric_version = 0.119.2+1.21.4

# Mod Versioning
mod_version = 1.7.0

# Naming
maven_group = io.github.nocomment1105.deepslatecutting
archives_base_name = deepslatecutting
enabled_platforms = fabric,neoforge

# Dependencies
architectury_version = 15.0.1

# Other
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=4096M
org.gradle.parallel=true
